name: HRespawn
version: '${project.version}'
main: me.hastly.hrespawn.Plugin
api-version: '1.16'
authors: [Hastly_]
description: Instant rebirth of a player with a title.
commands:
  hrespawn:
    aliases:
      - hresp
      - resp
permissions:
  hrespawn.reload:
    description: Ability to use /hrespawn reload
    default: op